---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: my-writer-binding
  # namespace: prod
roleRef:
  kind: ClusterRole
  name: writer
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: Group
  name: my-writer
  apiGroup: rbac.authorization.k8s.io
