apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gin-app-writer-binding
roleRef:
  kind: ClusterRole
  name: writer
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: gin-app-sa
  namespace: prod
