apiVersion: apps/v1
kind: Deployment
metadata:
  name: gin
  # namespace: lab
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  selector:
    matchLabels:
      app: gin
  template:
    metadata:
      labels:
        app: gin
    spec:
      containers:
      - name: gin
        image: ayushdumasia/go-bak
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 500m
            memory: 500Mi
          limits:
            cpu: 1000m
            memory: 1000Mi
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              key: RDS_DB
              name: gin-config
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_USER
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASS
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              key: DB_NAME
              name: gin-config
        - name: DB_PORT
          value: "3306"
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              key: AWS_REGION
              name: gin-config
        - name: S3_BUCKET
          valueFrom:
            configMapKeyRef:
              key: S3_BUCKET
              name: gin-config
        ports:
        - containerPort: 4000
