# backend_deployment_patch.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gin
spec:
  replicas: 2
  template:
    spec:
      serviceAccountName: gin-app-sa
    metadata:
      labels:
        app: gin # Ensure unique label
    # spec:
    #   containers:
    #   - name: gin
    #     image: ayushdumasia/go-bak:c59c2a3
