apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  template:
    spec:
      serviceAccountName: gin-app-sa
    metadata:
      labels:
        app: app
  replicas: 1
  # template:
  #   spec:
  #     containers:
  #     - name: app
  #       image: ayushdumasia/image-app:b359061
