apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod

resources:
- ../../base

images:
- name: ayushdumasia/go-drop
  newName: ayushdumasia/go-drop
  newTag: "4810873"
- name: ayushdumasia/pic-up
  newName: ayushdumasia/pic-up
  newTag: 2aba52f

patches:
- path: ns_patch.yaml
  target:
    kind: Namespace
- path: frontend_deployment_patch.yaml
  target:
    kind: Deployment
    name: app
- path: frontend_service_patch.yaml
  target:
    kind: Service
    name: app-service
- path: backend_deployment_patch.yaml
  target:
    kind: Deployment
    name: gin
- path: backend_service_patch.yaml
  target:
    kind: Service
    name: gin-service

configMapGenerator:
- behavior: replace
  literals:
  - AWS_REGION=ap-south-1
  - S3_BUCKET=prod-eks-gin-bucket-backend
  - RDS_DB=prod-eks-db.crskiw0kkxmi.ap-south-1.rds.amazonaws.com
  - DB_NAME=prodeksdb
  name: gin-config

generatorOptions:
  disableNameSuffixHash: true
